name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Run linter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "23.3.0"
      
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Install dependencies pyright
        run: |
          python -m pip install --upgrade pip
          pip install pyright
          python -m pip install -e .

      - name: Run pyright
        run: pyright